# Generated by Django 4.0.5 on 2022-08-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("options", "0004_auto_20190829_0936"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="help_text",
            field=models.TextField(blank=True, null=True, verbose_name="help text"),
        ),
        migrations.AddField(
            model_name="useroption",
            name="help_text",
            field=models.TextField(blank=True, null=True, verbose_name="help text"),
        ),
    ]
